theme: jekyll-theme-minimal
title: MEMEFANS Documentation
description: Technical documentation and guides for MEMEFANS platform
baseurl: ""
url: "https://memefans.github.io"
source: docs
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
  math_engine: mathjax
  hard_wrap: false

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: true

defaults:
  - scope:
      path: ""
    values:
      mermaid: true
